### PR TITLE
Database

### PR DESCRIPTION
**Pull request by phongatran**

### CODE REVIEW

**Comment by phongatran** [comment]
A face can be shared by multiple element types. How do you decide which one
it belongs to? Sure, we can pick the outside one to do the plotting, but
then we are ignoring the inner boundaries which is not anatomically correct
for any purpose other than plotting. One really should use
volface/boundary_faces(elem(elem(:,5)==ID,1:4)).

**Comment by fangq** [comment]
For colin27, the layered mesh are disconnected, so I can use finddisconnsurf() to extract each layer. see the last code section in http://mcx.sourceforge.net/cgi-bin/index.cgi?MMC/Colin27AtlasMesh/Version2

if your surfaces no longer have this property, you can use the following code to extract each layer

```
%% !!you must renumber your layer labels before using this code!!
newel=elem;
newel(newel(:,5)==6)=0;
wmface=volface(elem(newel(:,5)>=5,1:4));
gmface=volface(elem(newel(:,5)>=4,1:4));
csfface=volface(elem(newel(:,5)>=3,1:4));
skullface=volface(elem(newel(:,5)>=2,1:4));
sculpface=volface(elem(newel(:,5)>=1,1:4));
airface=volface(elem(newel(:,5)==0,1:4));

wmface(:,4)=5;
gmface(:,4)=4;
csfface(:,4)=3;
skullface(:,4)=2;
scalpface(:,4)=1;
airface(:,4)=6; % or 0

face=[scalpface; skullface; csfface; gmface; wmface; airface ];
```

I notice that your label numbering is inconsistent with my colin27 mesh. Please reorder your elem label first before running the above code, you should have

```
1 - scalp 
2- skull
3 - csf
4 - gmface
5 - wmface
0 or 6 - airface. maybe 0 is more intuitive
```

**Comment by fangq** [comment]
please update both elem and face, then save them, to reduce the turn-around time, send me by email your location of the folder, and I will check your new file again. I can then important them locally.

**Comment by fangq** [comment]
also, please remove all presence of boundary_faces() and replace it with volface. there is no need to maintain two functions that do the same thing.

**Comment by phongatran** [comment]
Same thought it seems. Ok I can do that. For the numbering, I thought we
were following the one that we are using in Brain2Mesh which is the reverse
other. Should we rewrite the Brain2Mesh order then? I think it makes sense
to do 1WM ==> 5 Scalp from the way we had the methodology worked out. That
is also the one we had in the Workshop.

**Pull request closed without merging**
